### ISSUE TITLE
使用add-attribution分支创建PR的指南

### ISSUE THREAD

**Issue by jokeryuyc** [jokeryuyc/astrbot-enhanced-chatsummary#8]
## 已完成的工作

我已经创建了一个名为`add-attribution`的分支，其中包含了以下更改：

1. **README.md**：添加了致谢部分，明确本项目基于[laopanmemz/astrbot_plugin_chatsummary](https://github.com/laopanmemz/astrbot_plugin_chatsummary)开发
2. **metadata.yaml**：更新了版本号、作者信息和添加了原始项目的引用

## 如何创建PR

您可以手动创建PR，步骤如下：

1. 访问 https://github.com/jokeryuyc/astrbot-enhanced-chatsummary/pulls
2. 点击 "New pull request" 按钮
3. 在 "base" 下拉菜单中选择 "main"
4. 在 "compare" 下拉菜单中选择 "add-attribution"
5. 点击 "Create pull request"
6. 填写标题：**添加原作者致谢和更新元数据**
7. 在描述框中添加以下内容：

```
## 更改内容

此PR添加了对原始项目的明确致谢，并更新了相关元数据。主要改动：

1. README.md 中添加了致谢部分，明确说明本项目基于 [laopanmemz/astrbot_plugin_chatsummary](https://github.com/laopanmemz/astrbot_plugin_chatsummary) 开发
2. metadata.yaml 中更新了：
   - 版本号更新为v1.0.3
   - 添加了原作者信息(original_author)
   - 添加了原始仓库链接(original_repo)
   - 更新了作者名为当前维护者

这些变更符合开源社区的最佳实践，确保正确归属原创工作和贡献。

## 后续工作

- 考虑后续版本更新时添加CONTRIBUTORS.md文件，详细记录所有贡献者
- 确保后续代码改动符合原项目许可证要求
```

8. 最后点击 "Create pull request" 完成PR创建

### README.md 中新增的致谢部分：

```markdown
## 致谢

本项目基于 [laopanmemz/astrbot_plugin_chatsummary](https://github.com/laopanmemz/astrbot_plugin_chatsummary) 开发，感谢原作者的工作和灵感。此增强版本在原有基础上添加了更多功能和优化，包括:
- 更丰富的消息类型支持
- 改进的错误处理机制
- 优化的代码结构
- 详细的安装文档和脚本
```

### metadata.yaml 中的更新：

```yaml
name: astrbot_plugin_chatsummary
desc: 一个基于LLM的智能历史聊天记录总结插件，支持结构化输出和自定义提示词。基于laopanmemz的原始项目开发。
help: |
  输入 /消息总结 + [空格] + 要总结的聊天记录数量（仅整数）触发消息总结。
  示例：/消息总结 100
  
  管理员可以使用调试模式：/消息总结 100 debug
version: v1.0.3
author: jokeryuyc
original_author: laopanmemz
original_repo: https://github.com/laopanmemz/astrbot_plugin_chatsummary
repo: https://github.com/jokeryuyc/astrbot-enhanced-chatsummary
tags:
  - 聊天
  - 总结
  - LLM
  - 工具
requirements:
  - astrbot>=0.1.0
```
